version: 2

jobs:
  build:
    docker:
        - image: kaleosoftware/circleci:1.5

    environment:
      RAILS_ENV: test
      _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
      JRUBY_OPTS: -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -X-C -Xcompile.invokedynamic=false --1.9 -J-Xmx2g


    steps:
      - checkout
      - setup_remote_docker
      - save_cache:
          paths:
            - '../.rvm/rubies'
            - "vendor/bundle"
            - elasticsearch-5.2.2
        
